---
- name: Solve mounts and link directories
  hosts: all
  sudo: yes

  tasks:
    - name: Establish No-Exec Mount in fstab
      mount:
        path: /HostHome
        src: HostHome
        fstype: vboxsf
        opts: _netdev,uid=1000,gid=1000,dmask=0077,fmask=0177
        state: mounted

    - name: Establish Exec Mount in fstab
      mount:
        path: /HostHomeExec
        src: HostHome
        fstype: vboxsf
        opts: _netdev,uid=1000,gid=1000,dmask=0077,fmask=0077
        state: mounted

    - name: Create missing paths
      file:
        path: "/home/{{ user_name }}{{ item }}"
        state: directory
        owner: 1000
        group: 1000
      with_items: "{{ create_dirs }}"
      when: create_dirs is defined and user_name is defined

    - name: Set up links
      file:
        path: "/home/{{ user_name }}{{ item.dst }}"
        src: "{{ item.src }}"
        state: link
        force: yes
        owner: 1000
        group: 1000
      with_items: "{{ link_dirs }}"
      when: link_dirs is defined and user_name is defined
    
    - name: Ensure Config Files refer to these links
      lineinfile:
        path: "/home/{{ user_name }}{{ item.file }}"
        line: "{{ item.line }}"
        state: present
        owner: 1000
        group: 1000
        mode: 0644
      with_items: "{{ set_env_vars }}"
      when: set_env_vars is defined and user_name is defined