---
#####################################################################
## Credentials
#####################################################################
## Default user is "ubuntu". Uncomment and change to create your 
## "own" user.
#
# original_user_name: ubuntu
# user_name: ubuntu
#
## Uncomment this to set the password to something you'll remember 
## (rather than the long hex string in 
## %HOME%\.vagrant.d\boxes\ubuntu*..*\Vagrantfile)
#
# user_password: SuperSecretPassword

#####################################################################
## Proxy
#####################################################################
# If you have an apt-cachier-ng proxy, or even just use a default 
# proxy that doesn't do NTLM authentication, stick it in here!
# apt_proxy: http://192.168.1.100:3142

#####################################################################
## Links
#####################################################################
## Set the following paths as appropriate
##
## Note that HostHome has been set Chmod to 600 for files, and 700 for directories.
## while HostHomeExec has 700 for files and 700 for directories.
#
#link_dirs:
#  - { src: "/HostHome/.dotfiles/openstack", dst: "/.config/openstack" }
#  - { src: "/HostHome/.dotfiles/ansible", dst: "/.config/ansible" }
#  - { src: "/HostHome/Sources", dst: "/Sources" }
#  - { src: "/HostHomeExec/Sources/bin", dst: "/bin" }
#
## These paths are ones which must be created before the above links can be created.
## Particularly, .config but you might want to include "Documents" or "bin"
#
#create_dirs:
#  - "/.config"
#
## These are lines that are added to your config files on provisioning
## You could include something about Byobu at this point, or starting the ssh-agent
#
#set_env_vars:
#  - { file: "/.bashrc", line: "ANSIBLE_VAULT_PASSWORD_FILE=~/.config/ansible/ansible-vault" }

#####################################################################
## Routine Post-Install Stuff
#####################################################################
## I typically install certain pacakges after each run. You might also want to do this
#
#install_apt_packages:
#  - byobu
#  - git-cola
#
## These are lines that are added to Cron jobs on your server
## Key values are:
## name, special_time, minute, hour, day, month, weekday, user, command, envvar
#
#set_cron_items:
#  - name: Set path for crontab
#    envvar: "/home/{{ user_name|default('ubuntu') }}/bin:/home/{{ user_name|default('ubuntu') }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
#  - name: Mount network share
#    special_time: reboot
#    command: sshfs user@192.168.1.1:/ /mnt
#  - name: Remind yourself to take a break
#    minute: */15
#    command: wall "Take a break"

#####################################################################
## Desktop Environment?
#####################################################################
## Do you want to run a full desktop environment? If so, uncomment 
## the following variable name for the environment you want.

# DesktopEnvironment: ubuntu-desktop
# DesktopEnvironment: kubuntu-desktop
# DesktopEnvironment: lubuntu-desktop
# DesktopEnvironment: xubuntu-desktop
# DesktopEnvironment: ubuntu-mate-desktop
# DesktopEnvironment: ubuntu-gnome-desktop

## Should the desktop environment pull the latest backports?
## Currently only Kubuntu has this.

# DesktopBackports: true
